# Shadowrocket – NetShort VIP 1 năm
[general]
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
bypass-system = true
dns-server = 8.8.8.8,1.1.1.1
ipv6 = false
prefer-ipv6 = false

[mitm]
hostname = buy.itunes.apple.com, api.netshort.app
tcp-fast-open = true
h2 = true
skip-cert-verify = true

[rewrite_local]
# Apple receipt
^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ script-response-body https://raw.githubusercontent.com/softwarescannerappnotprivatekeysir/node/refs/heads/main/appleReceipt.js
# NetShort profile
^https:\/\/api\.netshort\.app\/v1\/(user\/profile|subscription\/status) script-response-body https://raw.githubusercontent.com/softwarescannerappnotprivatekeysir/node/refs/heads/main/netShortVIP.js

[filter_local]
host-suffix, buy.itunes.apple.com, proxy
host-suffix, api.netshort.app, proxy
final, direct
